### PR TITLE
Feature: Add new FoxESS inverter protocol

### PR DESCRIPTION
**Pull request by dalathegreat**
### What
This PR implements a new inverter protocol, FoxESS

### Why
We emulate HV2600 V1, ECS4100 v1, HV2600 V2 packs, to improve compatibility with certain Foxess inverters that dont use Solax batteries

### How
Tested successfully by TheOfficialBatteryMan over on the Discord server!

image

### CODE REVIEW

**Comment by rand12345** [comment]
Please provide an explicit warning that this experimental code should not be used on FoxESS inverters without individual safety testing. There is no logic which instructs the inverter to stop charging on halt conditions such as SoC >= 100 or overvolt for starters (CAN frame 0x1876 byte 0). Incomplete protocol implementation has proven to be catastrophic for some FoxESS firmware variants.

Please see note 6 from [source material](https://github.com/FozzieUK/FoxESS-Canbus-Protocol/blob/main/README.md?plain=1#L82). 

> 0x1876 b0 bit 0 appears to be 1 when at maxsoc and BMS says charge is not allowed - when at 0 indicates charge is possible - addn'l note there is something more to it than this, it's not as straight forward - needs more testing to find what sets/unsets bit0 of byte0

An example of this can be found in my repository [here.](https://github.com/rand12345/Maxim178xx-ESP32-Arduino/blob/main/esp32-arduino/CAN_config.cpp#L381) An overly simple example of how this could be implementent is below.


``` C
  bool stop_charging = ((0 == max_charge_current) || (soc >= 100) || (cell_mv_max > max_cell_millivolts_limit));

  tx_msg.identifier = 0x1876;
  tx_msg.data[0] = char(stop_charging);
  ...
```

To be clear, KH model users will see potential overcharge conditions unless this software causes contractors open (if fitted) when scheduled charging occurs, **the inverter may not automatically halt charging when reported SoC >= 100 and for some firmware varients does not**. Whilst H and KH series are slightly different, the manufacturer is harmonizing their functional firmware differences between the models and does not provide a changelog for technical agents. Breaking changes are frequent and unannounced.


Additionally, the routine you have for reporting battery models ignores the defined protocol. One must account for a BMS master + slave packs and ensure that each "battery_type" is performed properly. Failure to do so creates problems for FoxESS cloud control for scheduled charging and strategies. Consider the BMS master to be device 0 and each subsequent slave battery to be > 0 as per [my example.](https://github.com/rand12345/Maxim178xx-ESP32-Arduino/blob/9b4284ce0d3c0639f11c68b125d440312f607e5d/esp32-arduino/CAN_config.cpp#L401)

There are further ideas in my repo to help with drastically simplifying code and logically generating the necessary CAN data based upon a [calcuated number of packs (+master)](https://github.com/rand12345/Maxim178xx-ESP32-Arduino/blob/9b4284ce0d3c0639f11c68b125d440312f607e5d/esp32-arduino/CAN_config.cpp#L179), [cells](https://github.com/rand12345/Maxim178xx-ESP32-Arduino/blob/9b4284ce0d3c0639f11c68b125d440312f607e5d/esp32-arduino/CAN_config.cpp#L267) and [temperatures](https://github.com/rand12345/Maxim178xx-ESP32-Arduino/blob/9b4284ce0d3c0639f11c68b125d440312f607e5d/esp32-arduino/CAN_config.cpp#L288).

I am not a C/C++ programmer per se and do not wish to add commits based on my own style. Please feel free to use my implentations in your own way with the usual accreditations.

Rand

**Comment by dalathegreat** [comment]
Massive thanks for the pointers @rand12345 ! 

I will get right on implementing the charge stop bit. We are doing testing on a Foxess H3 at the moment, but we need to get the CT clamps in order for more testing.

Very interesting to hear that the inverter does not stop charging at 100% SOC, does it also not respect the max allowed charge/discharge amps set in 0x1872?

```
  FOXESS_1872.data.u8[4] = (uint8_t)(max_charge_rate_amp * 10);
  FOXESS_1872.data.u8[5] = ((max_charge_rate_amp * 10) >> 8);
  FOXESS_1872.data.u8[6] = (uint8_t)(max_discharge_rate_amp * 10);
  FOXESS_1872.data.u8[7] = ((max_discharge_rate_amp * 10) >> 8);
```

Atleast on other inverters, when we set this to 0A allowed the charging stops. But I will get the charge stop bit implemented ASAP for next testing round!

**Comment by dalathegreat** [comment]
Hi again @rand12345 
I cannot use the source you linked, it is under a "PolyForm Strict License" which prevents the community funded programming I have set up via Youtube.

_Noncommercial Purposes
Any noncommercial purpose is a permitted purpose except for revenue generating projects (YouTube, sponsorship/membership, campaigns, or other funding streams) without prior permission._

So thanks for the pointer about the stop bit, cant use the linked source!

**Comment by dalathegreat** [comment]
Merging Foxess protocol to main. Been running stable for a few days! :partying_face:

**Pull request merged**
