### PR TITLE
Add new inverter implementation "Pylontech LV"

### PR DESCRIPTION
**Pull request by M4GNV5**
### What
Implementation of the talking-to-inverter side of the pylontech protocol

### Why
This is by far the most common protocol for LV batteries. Having this allows to talk to a wide range of inverters (Victron, SMA, Deye, ...).  See [this list starting on page 2](https://www.photovoltaikforum.com/core/attachment/307672-pylontech-compatible-list-v2-11-ess-neu-20221212-pdf/)

### How
Straightforward implementation of the CAN bus messages as documented [here](https://www.photovoltaikforum.com/core/attachment/77135-pylon-bms-protocol-can-can-20161103-pdf/)

### CODE REVIEW

**Review by dalathegreat — APPROVED** [review]
LGTM! Appreciate the work done here :raised_hands:

**Comment by dalathegreat** [comment]
Remember to edit Battery-Emulator/Software/src/inverter/INVERTERS.h and add Pylon_LV to it!

**Comment by M4GNV5** [comment]
Good catch. The webinterface also has a hardcoded list of all inverters. I will add it to both

**Review by dalathegreat — APPROVED** [review]

**Comment by M4GNV5** [comment]
The following CAN dump was obtained from the battery emulator with Twizy and Pylontech LV configured, there is one tiny fix I had to made to prevent division by 0 exceptions, after that this PR should be ready for merging:

```
  can0  351   [6]  00 00 00 00 00 00
  can0  355   [4]  00 00 00 00
  can0  356   [6]  00 00 00 00 00 00
  can0  359   [7]  00 00 00 00 01 50 4E
  can0  35C   [2]  00 00
  can0  35E   [8]  42 61 74 45 6D 75 4C 56
  can0  351   [6]  00 00 00 00 00 00
  can0  355   [4]  00 00 00 00
  can0  356   [6]  00 00 00 00 00 00
  can0  359   [7]  00 00 00 00 01 50 4E
  can0  35C   [2]  00 00
  can0  35E   [8]  42 61 74 45 6D 75 4C 56
  can0  351   [6]  00 00 00 00 00 00
  can0  355   [4]  00 00 00 00
  can0  356   [6]  00 00 00 00 00 00
  can0  359   [7]  00 00 00 00 01 50 4E
  can0  35C   [2]  00 00
  can0  35E   [8]  42 61 74 45 6D 75 4C 56
  can0  351   [6]  00 00 00 00 00 00
  can0  355   [4]  00 00 00 00
  can0  356   [6]  00 00 00 00 00 00
  can0  359   [7]  00 00 00 00 01 50 4E
  can0  35C   [2]  00 00
  can0  35E   [8]  42 61 74 45 6D 75 4C 56
  can0  351   [6]  2C 02 25 00 3A 01
  can0  355   [4]  40 02 BC 02
  can0  356   [6]  2C 02 40 01 AA 00
  can0  359   [7]  80 00 80 00 01 50 4E
  can0  35C   [2]  C0 00
  can0  35E   [8]  42 61 74 45 6D 75 4C 56
  can0  351   [6]  2C 02 25 00 3A 01
  can0  355   [4]  40 02 BC 02
  can0  356   [6]  2C 02 40 01 AA 00
  can0  359   [7]  80 00 80 00 01 50 4E
  can0  35C   [2]  C0 00
  can0  35E   [8]  42 61 74 45 6D 75 4C 56
  can0  351   [6]  2C 02 25 00 3A 01
  can0  355   [4]  40 02 BC 02
  can0  356   [6]  2C 02 40 01 AA 00
  can0  359   [7]  80 00 80 00 01 50 4E
  can0  35C   [2]  C0 00
  can0  35E   [8]  42 61 74 45 6D 75 4C 56
  can0  351   [6]  2C 02 25 00 3A 01
  can0  355   [4]  40 02 BC 02
  can0  356   [6]  2C 02 40 01 AA 00
  can0  359   [7]  80 00 80 00 01 50 4E
  can0  35C   [2]  C0 00
  can0  35E   [8]  42 61 74 45 6D 75 4C 56
  can0  351   [6]  2C 02 25 00 3A 01
  can0  355   [4]  40 02 BC 02
  can0  356   [6]  2C 02 40 01 AA 00
  can0  359   [7]  80 00 80 00 01 50 4E
  can0  35C   [2]  C0 00
  can0  35E   [8]  42 61 74 45 6D 75 4C 56
  can0  351   [6]  2C 02 25 00 3A 01
  can0  355   [4]  41 02 BC 02
  can0  356   [6]  2C 02 40 01 AA 00
  can0  359   [7]  80 00 80 00 01 50 4E
  can0  35C   [2]  C0 00
  can0  35E   [8]  42 61 74 45 6D 75 4C 56
  can0  351   [6]  2C 02 25 00 3A 01
  can0  355   [4]  41 02 BC 02
  can0  356   [6]  2C 02 40 01 AA 00
  can0  359   [7]  80 00 80 00 01 50 4E
  can0  35C   [2]  C0 00
  can0  35E   [8]  42 61 74 45 6D 75 4C 56
  can0  351   [6]  2C 02 25 00 3A 01
  can0  355   [4]  41 02 BC 02
  can0  356   [6]  2C 02 40 01 AA 00
  can0  359   [7]  80 00 80 00 01 50 4E
  can0  35C   [2]  C0 00
  can0  35E   [8]  42 61 74 45 6D 75 4C 56
  can0  351   [6]  2C 02 25 00 3A 01
  can0  355   [4]  41 02 BC 02
  can0  356   [6]  2C 02 40 01 AA 00
  can0  359   [7]  80 00 80 00 01 50 4E
  can0  35C   [2]  C0 00
  can0  35E   [8]  42 61 74 45 6D 75 4C 56
  can0  351   [6]  2C 02 25 00 3A 01
  can0  355   [4]  41 02 BC 02
  can0  356   [6]  2C 02 40 01 AA 00
  can0  359   [7]  80 00 80 00 01 50 4E
  can0  35C   [2]  C0 00
  can0  35E   [8]  42 61 74 45 6D 75 4C 56
  can0  351   [6]  2D 02 25 00 3A 01
  can0  355   [4]  43 02 BC 02
  can0  356   [6]  2D 02 40 01 AA 00
  can0  359   [7]  80 00 80 00 01 50 4E
  can0  35C   [2]  C0 00
  can0  35E   [8]  42 61 74 45 6D 75 4C 56
  can0  351   [6]  2D 02 25 00 3A 01
  can0  355   [4]  43 02 BC 02
  can0  356   [6]  2D 02 40 01 AA 00
  can0  359   [7]  80 00 80 00 01 50 4E
  can0  35C   [2]  C0 00
  can0  35E   [8]  42 61 74 45 6D 75 4C 56
```

**Comment by M4GNV5** [comment]
From my point of view this PR is now ready to merge. It might take some time (a few weeks) until I receive all PV components as well as adjust the in-house and in-vehicle wiring. Feel free to wait until then or merge it right away.

**Comment by dalathegreat** [comment]
Merging to main to make testing easier!

**Pull request merged**
