### PR TITLE
CHAdeMO Vehicles, Battery

### PR DESCRIPTION
**Pull request by NJbubo**
### What
I added the CHAdeMO GPIO configuration.

### Why
The inputs are not working.

### How
It is necessary to configure the GPIOs. In particular, setting the initial state of the outputs and enabling the inputs.

The inputs are not working with this modification!!!

### CODE REVIEW

**Comment by NJbubo** [comment]
I update CHADEMO-BATTERY.cpp. After this modification the INPUTs are worging good.

I think this place is not a correct place the GPIO config.

In my test, I use the CHADEMO_PIN_7 input as a start button.
I can't imagine how you intended to use "plug_inserted" as a signal according to the program.
I think the CHAdeMO connector pin 7 is connected directly to GND/0V when viewed from the side of the charger.

**Comment by dalathegreat** [comment]
@smaresca is the expert when it comes to the Chademo testing, got any opinions on this?

**Comment by smaresca** [comment]
@dalathegreat  noted, will review

**Comment by smaresca** [comment]
I am curious @NJbubo -- what model connector are you using?

**Comment by NJbubo** [comment]
Hi. I am using a SUMITUMO SEVD-11U connector.

**Pull request closed without merging**
