### PR TITLE
BMW i3: Make cellvoltages work for double-battery

### PR DESCRIPTION
**Pull request by dalathegreat**
### What
This PR fixes a bug causing cellvoltages not to be available for the second i3 battery in double-battery setups

### How
We copy the same method from battery1, forgotten during development

### CODE REVIEW

**Comment by lenvm** [comment]
Please also add the following code to `0x431` for battery2, as it is present for battery1, but not for battery2.

```
      if (battery_energy_content_maximum_kWh > 33) {
        detectedBattery = BATTERY_120AH;
      } else if (battery_energy_content_maximum_kWh > 20) {
        detectedBattery = BATTERY_94AH;
      } else {
        detectedBattery = BATTERY_60AH;
      }
```

**Comment by dalathegreat** [comment]
> Please also add the following code to `0x431` for battery2, as it is present for battery1, but not for battery2.

Well spotted, implemented autodetect for batter2 in [1c8aab9](https://github.com/dalathegreat/Battery-Emulator/pull/709/commits/1c8aab978f70ea8cb1229228f7e1d380e61c5df7)

**Review by lenvm — APPROVED** [review]

**Comment by pmajor021** [comment]
just found the last missing bit for displaying the call voltages for 2nd battery, it does not set the value of number_of_cells, so it is not displayed on the website

here is the way, who I fixed it on mine:

        case CELL_VOLTAGE_CELLNO:
          current_cell_polled++;
          if (current_cell_polled > 96) {
            datalayer.battery.info.number_of_cells = 97;
            #ifdef DOUBLE_BATTERY
              datalayer.battery2.info.number_of_cells = 97;
            #endif
            cmdState = CELL_VOLTAGE_CELLNO_LAST;
          } else {
            cmdState = CELL_VOLTAGE_CELLNO;

            BMW_6F4_CELL_VOLTAGE_CELLNO.data.u8[6] = current_cell_polled;
            transmit_can_frame(&BMW_6F4_CELL_VOLTAGE_CELLNO, can_config.battery);
#ifdef DOUBLE_BATTERY
            transmit_can_frame(&BMW_6F4_CELL_VOLTAGE_CELLNO, can_config.battery_double);
#endif
          }
          break;


I really need to learn, how to contribute more effectively to this project ;)

**Comment by pmajor021** [comment]
BMW-I3-BATTERY.cpp
```
@1051
          current_cell_polled++;
          if (current_cell_polled > 96) {
            datalayer.battery.info.number_of_cells = 97;
+            #ifdef DOUBLE_BATTERY
+              datalayer.battery2.info.number_of_cells = 97;
+            #endif
            cmdState = CELL_VOLTAGE_CELLNO_LAST;
          } else {
            cmdState = CELL_VOLTAGE_CELLNO;

```

**Pull request merged**
