### PR TITLE
Bugfix: Add messages needed for Solax Ultra

### LINKED ISSUE #650: Solax Ultra App Soc
### Expected Behavior

Soc in solax app

### Actual Behavior

Soc didnt work in app

### Steps to Reproduce the Problem

image
Sending can frames to inverter fixed the problem

### PR DESCRIPTION
**Pull request by dalathegreat**
### What
This PR fixes missing SOC% in app when using Solax Ultra inverter

### Why
Better user experience

### How
We send 5x CAN messages on boot towards the inverter. From testing, it appears that only sending these messages once seem to do the trick

Fixes #650

### CODE REVIEW

**Review by lenvm — APPROVED** [review]

**Comment by DeadmaroZ-TLOTL** [comment]
The first battery is now working fine, but the SOC (State of Charge) of the second battery is not showing up, and as a result, it does not work with the Solax Data Hub.

**Comment by dalathegreat** [comment]
@DeadmaroZ-TLOTL I suggest you make a new issue detailing the problems with the second battery. Please write as much info as possible

**Comment by DeadmaroZ-TLOTL** [comment]
12:31:12:3330 Rx 1 0x1871 x 8 03 06 18 09 0D 0B 1F 02 
12:31:12:4331 Rx 1 0x1871 x 8 01 00 01 00 00 00 00 00 
12:31:12:4334 Rx 1 0x1872 x 8 F8 0F F0 0A B4 01 F4 01 
12:31:12:4338 Rx 1 0x1890 x 8 10 00 02 00 00 00 00 00 
12:31:12:4341 Rx 1 0x187E x 8 CA 64 00 00 64 30 00 00 
12:31:12:4343 Rx 1 0x187D x 8 56 00 00 00 50 00 00 00 
12:31:12:4346 Rx 1 0x187C x 8 03 8A 13 30 00 00 00 00 
12:31:12:4349 Rx 1 0x187B x 8 04 00 00 08 00 00 48 00 
12:31:12:4352 Rx 1 0x187A x 8 01 50 B4 01 48 03 00 0E 
12:31:12:4355 Rx 1 0x1879 x 8 04 04 01 03 04 03 01 00 
12:31:12:4358 Rx 1 0x1878 x 8 07 0A 00 00 F7 8B 02 00 
12:31:12:4361 Rx 1 0x1877 x 8 00 00 10 10 5A 00 14 40 
12:31:12:4364 Rx 1 0x1876 x 8 00 00 11 0D 00 00 D5 0C 
12:31:12:4366 Rx 1 0x1875 x 8 DC 00 07 00 01 00 04 00 
12:31:12:4369 Rx 1 0x1874 x 8 E4 00 D6 00 21 00 21 00 
12:31:12:4372 Rx 1 0x1873 x 8 75 0E FD FF 30 00 D6 04

**Comment by dalathegreat** [comment]
@DeadmaroZ-TLOTL Unfortunately I think your setup is a bit too specific for anyone on the Dev team to be able to fix it. Since we fixed the Tesla by sending more CAN messages, I dont think we can fix the OEM Solax battery... Maybe reach out to Solax support (but don't mention the Tesla battery, or your warranty will be void and inverter risks being blocked)

**Comment by DeadmaroZ-TLOTL** [comment]
This is not my setup but a CAN log from a setup where there is 1. a Tesla battery and 2. a Solax Triple battery. This setup was only for logging CAN messages. If the Tesla battery is connected to the 2nd battery output, the percentage is not displayed on the main screen. The Data Hub also doesn’t work, even if the Tesla battery is connected to the 1st output.

**Pull request merged**
