### PR TITLE
Feature: BMW i3 cellvoltages + small fixes

### PR DESCRIPTION
**Pull request by dalathegreat**
### What
This PR adds cellvoltage monitoring for the BMW i3. It also fixes some minor issues that Havrla noticed while testing the code, like using wrong SOC% value and wrong capacity value.

### Why
Safer operation of the battery. SOC% is now using the display value, since the raw value can sometimes get "stuck" during recalibration. kWh remaining is also rewritten.

### How
Reverse engineering how the cellvalue reading worked, in cooperation with Havrla :raised_hands:

### CODE REVIEW

**Comment by dalathegreat** [comment]
Initial test showed that this did not work. Setting to WIP

**Comment by dalathegreat** [comment]
Help wanted, not sure why this is not working!

**Comment by ababians** [comment]
Can I help you?

**Comment by dalathegreat** [comment]
Massive thanks for the final push @odlg :raised_hands: You're awesome!

**Review by odlg — APPROVED** [review]

**Pull request merged**
