### PR TITLE
Update KIA-E-GMP-BATTERY.cpp

### PR DESCRIPTION
**Pull request by JorgenSeemann**
Removed cells with voltage below 1000mv in the set_cell_voltages routine

### CODE REVIEW

**Comment by dalathegreat** [comment]
Looks good @JorgenSeemann , but one of the build checks failed (we have very strict formatting rules)

I suggest you install the pre-commit check, it handles all formatting for you!

_The pre-commit git hook shall be installed locally by running the command line command `pre-commit install`, for instance using git-bash, in the location where the .pre-commit-config.yaml file is located._

Incase you do not want to do this setup, you can simply add two spaces here to get the check to pass
bild

**Review by JorgenSeemann — COMMENTED** [review]
spaces added

**Review by JorgenSeemann — COMMENTED** [review]
Added section to close contractor

**Comment by dalathegreat** [comment]
The addition caused more formatting issues. I really recommend installing the pre-commit git hook, it makes development so much easier! `pre-commit install` in command line

**Review by dalathegreat — APPROVED** [review]

**Pull request merged**
